#!/usr/bin/bash

if ! which pip2 >/dev/null 2>&1; then
  (>&2 echo "You need to install pip2")
  exit 1
fi

if ! (pip2 list | grep -q dotbot); then
  (>&2 echo "You need to install dotbot with pip2")
  exit 1
fi

dotbot -c ./install.yaml
